"""full schema

Revision ID: 67e15b9c27a4
Revises: 1da16302b46a
Create Date: 2024-03-15 14:38:10.983248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e15b9c27a4'
down_revision = '1da16302b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('affiliate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('affiliate_id')
    )
    op.create_table('subscription_plans',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('medias',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=25), nullable=True),
    sa.Column('size', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('renders',
    sa.Column('render_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('render_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renders')
    op.drop_table('medias')
    op.drop_table('subscription_plans')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
