"""back to down

Revision ID: 68a939f76fb0
Revises: d0be20be70dc
Create Date: 2024-04-17 12:55:41.136351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68a939f76fb0'
down_revision = 'd0be20be70dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('subscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription', mysql.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
