"""Changed affiliate key to string

Revision ID: 741c955e76fa
Revises: bd0d8a5d7f9e
Create Date: 2024-04-05 19:26:20.385571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '741c955e76fa'
down_revision = 'bd0d8a5d7f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
