"""Added path column to Render model

Revision ID: 82d77b41838e
Revises: 68a939f76fb0
Create Date: 2024-08-09 09:47:13.709269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d77b41838e'
down_revision = '68a939f76fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
