"""upadated subscription field in users to have default of 0

Revision ID: 878c1521a66d
Revises: 7f40e5266893
Create Date: 2024-04-10 20:04:39.045578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '878c1521a66d'
down_revision = '7f40e5266893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
