"""updated Affiliate table

Revision ID: 8d20b77b8390
Revises: 741c955e76fa
Create Date: 2024-04-10 13:08:06.228852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d20b77b8390'
down_revision = '741c955e76fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('addr1', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('addr2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('domain', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fb', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('twitch', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('paypal', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['twitch'])
        batch_op.create_unique_constraint(None, ['tiktok'])
        batch_op.create_unique_constraint(None, ['twitter'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['instagram'])
        batch_op.create_unique_constraint(None, ['paypal'])
        batch_op.create_unique_constraint(None, ['youtube'])
        batch_op.create_unique_constraint(None, ['domain'])
        batch_op.create_unique_constraint(None, ['telephone'])
        batch_op.create_unique_constraint(None, ['fb'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_added')
        batch_op.drop_column('paypal')
        batch_op.drop_column('twitch')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('youtube')
        batch_op.drop_column('instagram')
        batch_op.drop_column('fb')
        batch_op.drop_column('twitter')
        batch_op.drop_column('business_type')
        batch_op.drop_column('telephone')
        batch_op.drop_column('domain')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('addr2')
        batch_op.drop_column('addr1')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
