"""Media data -> path and unique

Revision ID: bd0d8a5d7f9e
Revises: cb0866c20024
Create Date: 2024-03-21 21:43:20.086360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd0d8a5d7f9e'
down_revision = 'cb0866c20024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['path'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
