"""changed data field to path field

Revision ID: cb0866c20024
Revises: d36a24826db8
Create Date: 2024-03-21 13:20:12.385268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0866c20024'
down_revision = 'd36a24826db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
