"""removed uniqueness from social links

Revision ID: d0be20be70dc
Revises: 8d20b77b8390
Create Date: 2024-04-10 14:24:14.301969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0be20be70dc'
down_revision = '8d20b77b8390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=50), nullable=False))
        batch_op.drop_index('fb')
        batch_op.drop_index('instagram')
        batch_op.drop_index('tiktok')
        batch_op.drop_index('twitch')
        batch_op.drop_index('twitter')
        batch_op.drop_index('youtube')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.create_index('youtube', ['youtube'], unique=True)
        batch_op.create_index('twitter', ['twitter'], unique=True)
        batch_op.create_index('twitch', ['twitch'], unique=True)
        batch_op.create_index('tiktok', ['tiktok'], unique=True)
        batch_op.create_index('instagram', ['instagram'], unique=True)
        batch_op.create_index('fb', ['fb'], unique=True)
        batch_op.drop_column('key')

    # ### end Alembic commands ###
