"""add fks to users

Revision ID: d22cad86e7dc
Revises: 67e15b9c27a4
Create Date: 2024-03-15 14:39:18.327684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22cad86e7dc'
down_revision = '67e15b9c27a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'affiliates', ['affiliate_id'], ['affiliate_id'])
        batch_op.create_foreign_key(None, 'subscription_plans', ['subscription_id'], ['plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('affiliate_id')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
